# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lmm_pxem <- function(y, X, W, tol, maxIter) {
    .Call(`_iGREX_lmm_pxem`, y, X, W, tol, maxIter)
}

iGREX_Kg <- function(y, X1, X2, W1, tol, maxIter) {
    .Call(`_iGREX_iGREX_Kg`, y, X1, X2, W1, tol, maxIter)
}

iGREX_raw <- function(prefix_eQTL_geno, prefix_GWAS, gene_expr, cov_eQTL, cov_GWAS, whCol, bw, subsample) {
    .Call(`_iGREX_iGREX_raw`, prefix_eQTL_geno, prefix_GWAS, gene_expr, cov_eQTL, cov_GWAS, whCol, bw, subsample)
}

iGREX_init <- function(prefix_eQTL_geno, prefix_GWAS, gene_expr, cov_eQTL, cov_GWAS, trans_eQTL, whCol, bw, subsample) {
    .Call(`_iGREX_iGREX_init`, prefix_eQTL_geno, prefix_GWAS, gene_expr, cov_eQTL, cov_GWAS, trans_eQTL, whCol, bw, subsample)
}

iGREXs_init <- function(prefix_eQTL_geno, prefix_GWAS, gene_expr, Z_score, cov_eQTL, cov_GWAS, trans_eQTL, bw) {
    .Call(`_iGREX_iGREXs_init`, prefix_eQTL_geno, prefix_GWAS, gene_expr, Z_score, cov_eQTL, cov_GWAS, trans_eQTL, bw)
}

